name: E2E
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci

      # If your tests expect Firebase Emulators / dev server:
      # - run: npm run emu &> emu.log &
      # - run: npm run dev &> dev.log &
      # - run: npx wait-on http://localhost:3000

      # Install browsers + system deps for Playwright
      - uses: microsoft/playwright-github-action@v1
      - run: npx playwright install --with-deps

      - run: npm run test:e2e

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
