name: E2E
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # Keep envs in one place; adjust names to your project
    env:
      NODE_ENV: test
      NEXT_TELEMETRY_DISABLED: '1'
      PORT: 9002

      # --- Firebase emulator mode ---
      FIREBASE_PROJECT_ID: demo-student-portal          # must match your seed/emulator config
      FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
      FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9099

      # Admin SDK init (your code reads FIREBASE_SERVICE_ACCOUNT JSON or individual vars)
      # Put the FULL service-account JSON as a single-line secret in repo settings
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # Install browsers + system deps for Playwright
      - uses: microsoft/playwright-github-action@v1
      - run: npx playwright install --with-deps

      # --- Start Firebase emulators (background) ---
      # expects you have "emu" script, e.g. "firebase emulators:start --only auth,firestore --project $FIREBASE_PROJECT_ID"
      - name: Start Firebase emulators
        run: npm run emu &> emu.log &

      - name: Wait for emulators
        run: npx wait-on tcp:8080 tcp:9099

      # --- Seed dev data into emulators ---
      # expects you have "seed" script that writes admin/teacher/student/class/material/assignment/flashcards
      - name: Seed dev data
        run: npm run seed

      # --- Build & start Next.js on :9002 (background) ---
      - name: Build Next.js
        run: npm run build

      - name: Start Next.js
        run: npx next start -p $PORT &> web.log &

      - name: Wait for web
        run: npx wait-on http://localhost:$PORT

      # --- Run E2E ---
      - name: Run Playwright E2E
        run: npm run test:e2e

      # Always upload logs & report for debugging
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            emu.log
            web.log
